version: '2'
services:
  app:
    build: ./
    restart: always
    ports:
      - 443:443
    environment:
      - PORT=443
      - NODE_MAX_MEM=2000
networks:
  default:
    external:
      name: applications-network
