version: '2'
services:
  app:
    build: ./
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - NODE_MAX_MEM=2000
networks:
  default:
    external:
      name: applications-network